-- Phase 1 permission catalogue and default role bundles (docs/architecture/05 §3).
-- Societies can edit their copies of these roles; templates only seed new societies.

INSERT INTO permission (code, module, action, description) VALUES
  ('society:manage',        'society',   'manage',        'Edit society settings, towers, flats, locations, facilities'),
  ('member:manage',         'member',    'manage',        'Add, move and end residents and memberships'),
  ('member:view',           'member',    'view',          'See resident records'),
  ('directory:view',        'directory', 'view',          'See the opt-in resident directory'),
  ('import:run',            'import',    'run',           'Bulk Excel onboarding'),
  ('gate:entry',            'gate',      'entry',         'Log visitors, deliveries and staff at the gate'),
  ('gate:log-view',         'gate',      'log-view',      'See the gate log for the whole society'),
  ('gatepass:create',       'gatepass',  'create',        'Pre-approve guests for own flat'),
  ('gatepass:view',         'gatepass',  'view',          'See own flat gate passes and visitors'),
  ('gate:approve',          'gate',      'approve',       'Approve or deny entries for own flat'),
  ('sos:raise',             'sos',       'raise',         'Raise an SOS alert'),
  ('incident:report',       'incident',  'report',        'Report an incident'),
  ('incident:manage',       'incident',  'manage',        'Handle incidents and RCA'),
  ('staff:attendance',      'staff',     'attendance',    'Record domestic and society staff attendance'),
  ('bill:generate',         'bill',      'generate',      'Run and publish bill runs'),
  ('bill:view',             'bill',      'view',          'See all bills'),
  ('bill:view-own',         'bill',      'view-own',      'See own flat bills'),
  ('bill:pay',              'bill',      'pay',           'Pay own flat bills'),
  ('payment:record',        'payment',   'record',        'Record offline payments'),
  ('payment:view',          'payment',   'view',          'See all payments and receipts'),
  ('expense:record',        'expense',   'record',        'Record expenses'),
  ('expense:view',          'expense',   'view',          'See expenses'),
  ('budget:approve',        'budget',    'approve',       'Approve budgets'),
  ('ledger:view',           'ledger',    'view',          'See the ledger and exports'),
  ('vendorpayment:record',  'vendorpayment', 'record',    'Record vendor payments'),
  ('asset:manage',          'asset',     'manage',        'Create and edit assets, QR, warranty, AMC'),
  ('asset:view',            'asset',     'view',          'See assets and their history'),
  ('pm:manage',             'pm',        'manage',        'Plan preventive maintenance'),
  ('pm:execute',            'pm',        'execute',       'Carry out PM tasks'),
  ('complaint:create',      'complaint', 'create',        'Raise complaints'),
  ('complaint:view',        'complaint', 'view',          'See all complaints'),
  ('complaint:manage',      'complaint', 'manage',        'Triage, route and resolve complaints'),
  ('breakdown:report',      'breakdown', 'report',        'Report breakdowns'),
  ('jobcard:view',          'jobcard',   'view',          'See all job cards'),
  ('jobcard:assign',        'jobcard',   'assign',        'Assign job cards'),
  ('jobcard:work',          'jobcard',   'work',          'Work on assigned job cards'),
  ('jobcard:approve',       'jobcard',   'approve',       'Verify and approve completed job cards'),
  ('jobcard:close',         'jobcard',   'close',         'Close job cards'),
  ('spare:issue-request',   'spare',     'issue-request', 'Request spares'),
  ('reading:record',        'reading',   'record',        'Record utility readings'),
  ('checklist:execute',     'checklist', 'execute',       'Fill checklists'),
  ('checklist:manage',      'checklist', 'manage',        'Build checklist templates'),
  ('signoff:daily',         'signoff',   'daily',         'Daily manager sign-off'),
  ('notice:publish',        'notice',    'publish',       'Publish notices'),
  ('notice:view',           'notice',    'view',          'Read notices'),
  ('poll:create',           'poll',      'create',        'Create polls'),
  ('poll:vote',             'poll',      'vote',          'Vote in polls'),
  ('event:manage',          'event',     'manage',        'Create and run community events'),
  ('booking:create',        'booking',   'create',        'Book facilities'),
  ('booking:manage',        'booking',   'manage',        'Manage all bookings and rules'),
  ('workflow:manage',       'workflow',  'manage',        'Configure approval workflows and SLA policies'),
  ('approval:decide',       'approval',  'decide',        'Approve or reject workflow tasks'),
  ('po:approve',            'po',        'approve',       'Approve purchase orders'),
  ('amc:visit',             'amc',       'visit',         'Record AMC visits'),
  ('invoice:submit',        'invoice',   'submit',        'Submit vendor invoices'),
  ('mis:view',              'mis',       'view',          'See MIS reports'),
  ('dashboard:view',        'dashboard', 'view',          'See the morning dashboard'),
  ('audit:view',            'audit',     'view',          'See the audit trail'),
  ('role:manage',           'role',      'manage',        'Edit roles and assign them'),
  ('user:manage',           'user',      'manage',        'Invite and block users'),
  ('settings:manage',       'settings',  'manage',        'Society configuration');

INSERT INTO role_template (code, name, description, permissions) VALUES
  ('RWA_COMMITTEE', 'RWA committee', 'Governance, approvals and MIS',
   '{budget:approve,po:approve,mis:view,dashboard:view,notice:publish,notice:view,poll:create,poll:vote,event:manage,approval:decide,audit:view,bill:view,payment:view,expense:view,ledger:view,complaint:view,jobcard:view,asset:view,member:view,directory:view}'),
  ('ESTATE_MANAGER', 'Estate manager', 'Runs all estate operations',
   '{society:manage,member:manage,member:view,directory:view,import:run,gate:log-view,incident:manage,incident:report,staff:attendance,asset:manage,asset:view,pm:manage,pm:execute,complaint:view,complaint:manage,breakdown:report,jobcard:view,jobcard:assign,jobcard:approve,jobcard:close,reading:record,checklist:manage,checklist:execute,signoff:daily,notice:publish,notice:view,poll:create,event:manage,booking:manage,workflow:manage,approval:decide,mis:view,dashboard:view,audit:view,role:manage,user:manage,settings:manage,bill:view,payment:view,expense:view}'),
  ('FACILITY_MANAGER', 'Facility manager', 'Utilities, checklists and staff',
   '{asset:view,pm:manage,pm:execute,complaint:view,complaint:manage,breakdown:report,jobcard:view,jobcard:assign,jobcard:approve,reading:record,checklist:manage,checklist:execute,staff:attendance,incident:report,incident:manage,dashboard:view,notice:view}'),
  ('ENGINEER', 'Engineer', 'Senior technical staff',
   '{asset:view,pm:execute,jobcard:view,jobcard:work,jobcard:assign,breakdown:report,spare:issue-request,reading:record,checklist:execute,incident:report}'),
  ('TECHNICIAN', 'Technician', 'Plumber, electrician, lift, DG and other trades',
   '{asset:view,pm:execute,jobcard:work,breakdown:report,spare:issue-request,reading:record,checklist:execute,incident:report}'),
  ('HOUSEKEEPING', 'Housekeeping', 'Cleaning and common-area staff',
   '{checklist:execute,staff:attendance,incident:report,breakdown:report}'),
  ('GUARD', 'Guard', 'Gate and security staff',
   '{gate:entry,gate:log-view,staff:attendance,sos:raise,incident:report,breakdown:report}'),
  ('ACCOUNTS', 'Accounts', 'Billing, payments and expenses',
   '{bill:generate,bill:view,payment:record,payment:view,expense:record,expense:view,ledger:view,vendorpayment:record,mis:view,dashboard:view}'),
  ('VENDOR', 'Vendor', 'Assigned work only',
   '{jobcard:work,amc:visit,invoice:submit}'),
  ('RESIDENT_OWNER', 'Owner', 'Flat owner',
   '{gatepass:create,gatepass:view,gate:approve,sos:raise,bill:view-own,bill:pay,complaint:create,booking:create,notice:view,poll:vote,directory:view}'),
  ('RESIDENT_TENANT', 'Tenant', 'Flat tenant',
   '{gatepass:create,gatepass:view,gate:approve,sos:raise,bill:view-own,bill:pay,complaint:create,booking:create,notice:view,poll:vote,directory:view}'),
  ('RESIDENT_FAMILY', 'Family member', 'Family member of an owner or tenant',
   '{gatepass:create,gatepass:view,gate:approve,sos:raise,complaint:create,booking:create,notice:view,poll:vote}');
