package in.societyos.media.media.domain;

import java.time.Duration;
import java.util.Locale;
import java.util.Set;

/**
 * Why a file is stored. Each purpose fixes the owning service, the allowed content types, the size
 * limit, whether it is private to its uploader, and its default retention.
 */
public enum MediaPurpose {
  VISITOR_PHOTO("security", Kinds.IMAGES, mb(5), false, Duration.ofDays(180)),
  STAFF_PHOTO("society", Kinds.IMAGES, mb(5), false, null),
  KYC_DOCUMENT("society", Kinds.IMAGES_AND_PDF, mb(10), true, null),
  COMPLAINT_PHOTO("ticket", Kinds.IMAGES, mb(10), false, null),
  JOBCARD_EVIDENCE("ticket", Kinds.IMAGES_AND_VIDEO, mb(50), false, null),
  ASSET_PHOTO("asset", Kinds.IMAGES, mb(10), false, null),
  ASSET_DOCUMENT("asset", Kinds.IMAGES_AND_PDF, mb(20), false, null),
  RECEIPT_PDF("billing", Kinds.PDF, mb(5), false, null),
  NOTICE_ATTACHMENT("community", Kinds.IMAGES_AND_PDF, mb(10), false, null),
  COMPLIANCE_DOCUMENT("compliance", Kinds.IMAGES_AND_PDF, mb(25), false, null),
  CHECKLIST_EVIDENCE("utility", Kinds.IMAGES, mb(10), false, null),
  AVATAR("identity", Kinds.IMAGES, mb(2), false, null),
  /** Generated by media-service itself; never requested by a client. */
  THUMBNAIL("media", Set.of("image/jpeg"), mb(1), false, null);

  private final String ownerService;
  private final Set<String> contentTypes;
  private final long maxBytes;
  private final boolean privateToUploader;
  private final Duration defaultRetention;

  MediaPurpose(String ownerService, Set<String> contentTypes, long maxBytes, boolean privateToUploader,
      Duration defaultRetention) {
    this.ownerService = ownerService;
    this.contentTypes = contentTypes;
    this.maxBytes = maxBytes;
    this.privateToUploader = privateToUploader;
    this.defaultRetention = defaultRetention;
  }

  public String ownerService() {
    return ownerService;
  }

  public Set<String> contentTypes() {
    return contentTypes;
  }

  public long maxBytes() {
    return maxBytes;
  }

  public boolean privateToUploader() {
    return privateToUploader;
  }

  /** Null means kept until deleted by its owner. */
  public Duration defaultRetention() {
    return defaultRetention;
  }

  public boolean clientUploadable() {
    return this != THUMBNAIL;
  }

  /** Normalises {@code image/JPEG; charset=x} to {@code image/jpeg}. */
  public static String normaliseContentType(String contentType) {
    if (contentType == null) {
      return "";
    }
    int semi = contentType.indexOf(';');
    String base = semi < 0 ? contentType : contentType.substring(0, semi);
    return base.trim().toLowerCase(Locale.ROOT);
  }

  /** Returns a rule-violation code, or null when the upload is acceptable. */
  public String violation(String contentType, long sizeBytes) {
    if (!clientUploadable()) {
      return "PURPOSE_NOT_UPLOADABLE";
    }
    if (!contentTypes.contains(normaliseContentType(contentType))) {
      return "CONTENT_TYPE_NOT_ALLOWED";
    }
    if (sizeBytes <= 0) {
      return "EMPTY_FILE";
    }
    if (sizeBytes > maxBytes) {
      return "FILE_TOO_LARGE";
    }
    return null;
  }

  private static long mb(int n) {
    return n * 1024L * 1024L;
  }

  private static final class Kinds {
    static final Set<String> IMAGES = Set.of("image/jpeg", "image/png", "image/webp");
    static final Set<String> PDF = Set.of("application/pdf");
    static final Set<String> IMAGES_AND_PDF = Set.of("image/jpeg", "image/png", "image/webp", "application/pdf");
    static final Set<String> IMAGES_AND_VIDEO = Set.of("image/jpeg", "image/png", "image/webp", "video/mp4");
  }
}
